name: Build and Release

on:
  workflow_dispatch:
  push:
    tags:
      - '[0-9]+.[0-9]+.[0-9]+-win7'

jobs:
  build:
    runs-on: windows-latest
    permissions:
      contents: write
    steps:
      - name: Checkout
        uses: actions/checkout@v6

      # - name: Add Win10 SDK to PATH
      #   run: Add-Content $env:GITHUB_PATH "C:\Program Files (x86)\Windows Kits\10\bin\10.0.26100.0\x64"

      - name: Build
        run: cmd /c build.bat

      - name: Create msi
        run: cmd /c installer\build.bat

      - name: Prepare assets
        run: |
          foreach ($i in @('x86', 'amd64', 'arm64')) {
            7z a -tzip amneziawg-$i.zip .\$i\amneziawg.exe .\installer\dist\amneziawg-$i-*.msi
          }

      - name: Upload assets to release
        uses: softprops/action-gh-release@v2
        with:
          fail_on_unmatched_files: true
          prerelease: false
          target_commitish: ${{ github.sha }}
          body: |
            AmneziaWG compatible with Windows 7

            * Built with go1.21.4 to make it possible to run on Windows 7
            * Restore multiple simultaneous tunnels feature (from amnezia-vpn/amneziawg-windows-client#30)

            MSI installer files are unsigned and provided AS-IS.
          files: amneziawg-*.zip
